version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_user_api_db
    volumes:
      - ./storage/migrations.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  app:
    build:
      context: ./
    # image: guntoroyk/go-user-api:1.0.0
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db